### PR TITLE
Add the brank DebotStrategyBuilder class in the debot-no-op

### PR DESCRIPTION
**Pull request by androhi**
## Purpose

- When you run a release build, it will be modified to become error.

## Did it

- Create the brank DebotStrategyBuilder.java.
- Modify sample app for using custom menu.

### CODE REVIEW

**Comment by tomoima525** [comment]
Thanks for the PR! It is really helpful. I was completely out of mind about `DebotStrategyBuilder` for no-op.

I checked the source code of no-op again and realised `DebotAnnotation.java` is missing as well.
Is it OK for you to create annotation directory and add `DobotAnnotation.java` ?

```
debot-no-op
└ src.main.java.com.tomoima.debot
     └annotation
         └DebotAnnotation.java
```

**Comment by androhi** [comment]
Thank you for reply.
I tried a release build after adding the DebotAnnotaion class. Then, I noticed that the additional DebotCallActivityMethodStrategy class also neccesary.

Example, case of the following Application class.

```java
public class MyApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        ...
        DebotStrategyBuilder builder = new DebotStrategyBuilder.Builder(this)
                .registerMenu("input", new DebotCallActivityMethodStrategy("debugInput"))
                .build();
        DebotConfigurator.configureWithCustomizedMenu(this, builder.getStrategyList());
    }
```

Please review the added change.

**Comment by tomoima525** [comment]
You are right, thanks a lot!

LGTM

**Comment by androhi** [comment]
I'm glad to help. :smile:

**Pull request merged**
